on:

  push:
    branches:
    - master

  workflow_dispatch: {}

jobs:

  get-pr-info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: commit_id
      shell: bash
      run: |
        echo "commit_hash=$(git rev-parse HEAD)" | tee $GITHUB_OUTPUT
    - id: pr_id
      uses: actions/github-script@v6
      with:
        debug: true
        script: |
          const commit_hash = "${{ steps.commit_id.outputs.commit_hash }}"
          const { data: { items } } = await github.rest.search.issuesAndPullRequests({
            q: `${commit_hash} type:pr is:merged`
          });
          console.log(items)
