name: PR Build
on:

  pull_request:
    branches:
    - master

  workflow_dispatch: {}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - id: check_ancestry
      name: Check branch ancestry
      shell: bash
      run: |
        if $(git merge-base --is-ancestor origin/master ${GITHUB_REF#refs/heads/}); then
          echo "Branch ${GITHUB_REF#refs/heads/} verified to have linear history with master."
        else
          echo "History for branch ${GITHUB_REF#refs/heads/} is not linear with master, please rebase or merge from master and try again."
          exit 1
        fi

    - id: pr_event_info
      name: PR event info test
      shell: bash
      run: |
        cat << EOF
        ${{ github.event }}
        EOF

