name: Versioning
on:

  pull_request:
    branches:
    - master

  workflow_dispatch: {}

jobs:

  make-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: make_version
      uses: actions/github-script@v6
      with:
        debug: true
        script: |
          const { execSync } = require('child_process');

          // Get latest tag and parse into object
          let v_string = execSync(
            'git tag --list | sort --sort=version | tail -n 1',
            { encoding: 'utf-8' }
          );
          let v_object = ((v = v_string.split(".")) => {
            return {
              major: Number(v[0]),
              minor: Number(v[1]),
              patch: Number(v[2])
            }
          })();
          console.log(`Found tag with version ${v_string}`);

          // Increase relevant version
          switch ( (context.payload.pull_request.title.match(/\[(MAJOR|MINOR|PATCH)\]/) || ['',''])[1] ) {

            case 'MAJOR':
              v_object.major += 1;
              break;

            case 'MINOR':
              v_object.minor += 1;
              break;

            case 'PATCH':
              v_object.patch += 1;
              break;

            default:
              console.error('Missing version change tag in PR title');
              process.exit(1);
          }

          console.log(`Last version: ${v_string}`);
          console.log(`Next version: ${v_object.major}.${v_object.minor}.${v_object.patch}`);

