name: YAML
on:

  workflow_dispatch: {}

jobs:
  yaml:
    runs-on: ubuntu-latest
    steps:

    - name: Write some yaml
      run: |
        echo "---
        some: yaml
        more: yaml
        this:
          is:
            more: yaml
        " | tee test-file.yaml

    - name: Read some yaml
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');

          try {
            console.log('Trying to load js-yaml...')
            const jsyaml = require('js-yaml');
            const doc = yaml.load(fs.readFileSync('test-file.yaml', 'utf8'));
            console.log(doc);
            return
          } catch (e) {
            console.log(e.code);
          }

          try {
            console.log('Trying to load YAML...')
            const YAML = require('yaml');
            const doc = YAML.parse(fs.readFileSync('test-file.yaml', 'utf8'));
            console.log(doc);
            return
          } catch (e) {
            console.log(e.code);
          }


